
services:
  postgres:
    image: postgres:16
    container_name: minimarket_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    networks:
      - minimarket_network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: minimarket_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init-scripts/clickhouse/init_clickhouse.sql:/docker-entrypoint-initdb.d/init_clickhouse.sql
    networks:
      - minimarket_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: minimarket_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - clickhouse
    networks:
      - minimarket_network

  superset:
    build:
      context: ./superset
    container_name: minimarket_superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - clickhouse
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin
        --username admin
        --firstname Superset
        --lastname Admin
        --email admin@example.com
        --password admin || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - minimarket_network

  pipeline:
    build:
      context: ./pipeline
    container_name: minimarket_pipeline
    env_file:
      - .env
    volumes:
      - ./pipeline:/app
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - minimarket_network
    command: ["python", "main.py"]

networks:
  minimarket_network:
    driver: bridge

volumes:
  postgres_data:
  clickhouse_data:
  superset_home:
