
services:
  postgres:
    image: postgres:16
    container_name: minimarket_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: minimarket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: minimarket_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init-scripts/clickhouse/init_clickhouse.sql:/docker-entrypoint-initdb.d/init_clickhouse.sql

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: minimarket_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - clickhouse

  superset:
    build:
      context: ./superset
    container_name: minimarket_superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: "change-this-secret-key"
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - clickhouse
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin
        --username admin
        --firstname Superset
        --lastname Admin
        --email admin@example.com
        --password admin || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes:
  postgres_data:
  clickhouse_data:
  superset_home: